/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

import javax.swing.JOptionPane;
import locadora.controller.UsuarioController;

/**
 *
 * @author pedro
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {
    private TelaPrincipal telaPrincipal;
    private Integer codUsuario = 0;
    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroUsuario() {
        initComponents();
    }
    
    public TelaCadastroUsuario(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2Nome = new javax.swing.JLabel();
        jLabel4CPF = new javax.swing.JLabel();
        jLabel5Email = new javax.swing.JLabel();
        jLabel6Endereco = new javax.swing.JLabel();
        jTextField1Nome = new javax.swing.JTextField();
        jTextField3CPF = new javax.swing.JTextField();
        jTextField4Email = new javax.swing.JTextField();
        jTextField5Endereco = new javax.swing.JTextField();
        jButton1Consultar = new javax.swing.JButton();
        jButton2Cancelar = new javax.swing.JButton();
        jButton3Limpar = new javax.swing.JButton();
        jButton4Salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Jogos");

        jLabel1.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRAR USUARIO");

        jLabel2Nome.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jLabel2Nome.setText("Nome:");

        jLabel4CPF.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jLabel4CPF.setText("CPF:");

        jLabel5Email.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel5Email.setText("Email:");

        jLabel6Endereco.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jLabel6Endereco.setText("Endereço:");

        jTextField1Nome.setFont(new java.awt.Font("Nimbus Sans", 0, 16)); // NOI18N

        jTextField3CPF.setFont(new java.awt.Font("Nimbus Sans", 0, 16)); // NOI18N

        jTextField4Email.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N

        jTextField5Endereco.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N

        jButton1Consultar.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jButton1Consultar.setText("Consultar");
        jButton1Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultarActionPerformed(evt);
            }
        });

        jButton2Cancelar.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jButton2Cancelar.setText("Cancelar");
        jButton2Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CancelarActionPerformed(evt);
            }
        });

        jButton3Limpar.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jButton3Limpar.setText("Limpar");
        jButton3Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3LimparActionPerformed(evt);
            }
        });

        jButton4Salvar.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jButton4Salvar.setText("Salvar");
        jButton4Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4SalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton4Salvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3Limpar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2Cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1Consultar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2Nome)
                            .addComponent(jLabel4CPF)
                            .addComponent(jLabel5Email, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4Email, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6Endereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Nome)
                    .addComponent(jTextField1Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4CPF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5Email))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6Endereco)
                    .addComponent(jTextField5Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1Consultar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3Limpar)
                        .addComponent(jButton4Salvar)
                        .addComponent(jButton2Cancelar)))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4SalvarActionPerformed
        boolean sucesso;
        
        try{
            UsuarioController usuarioController = new UsuarioController();
            sucesso = usuarioController.cadastrarUsuario(jTextField1Nome.getText(),jTextField3CPF.getText(), jTextField4Email.getText(), jTextField5Endereco.getText());
            if(sucesso == true){
                JOptionPane.showMessageDialog(null, "Jogo guardado");
            }else {
                JOptionPane.showMessageDialog(null, "Preencha corretamente");
            }
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton4SalvarActionPerformed

    private void jButton3LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3LimparActionPerformed
        jTextField1Nome.setText("");
        jTextField3CPF.setText("");
        jTextField4Email.setText("");
        jTextField5Endereco.setText("");
    }//GEN-LAST:event_jButton3LimparActionPerformed

    private void jButton2CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CancelarActionPerformed
        this.dispose();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton2CancelarActionPerformed

    private void jButton1ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Consultar;
    private javax.swing.JButton jButton2Cancelar;
    private javax.swing.JButton jButton3Limpar;
    private javax.swing.JButton jButton4Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2Nome;
    private javax.swing.JLabel jLabel4CPF;
    private javax.swing.JLabel jLabel5Email;
    private javax.swing.JLabel jLabel6Endereco;
    private javax.swing.JTextField jTextField1Nome;
    private javax.swing.JTextField jTextField3CPF;
    private javax.swing.JTextField jTextField4Email;
    private javax.swing.JTextField jTextField5Endereco;
    // End of variables declaration//GEN-END:variables


  
}
