package locadora.view;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import locadora.dao.ExceptionDAO;
import locadora.model.Protagonista;
import locadora.controller.ProtagonistaController;

/**
 *
 * @author pedro
 */
public class TelaCadastroProtagonista extends javax.swing.JFrame {
        private TelaPrincipal telaPrincipal;
    /**
     * Creates new form TelaCadastroProtagonista
     */
    public TelaCadastroProtagonista() {
        initComponents();
    }
    
    public TelaCadastroProtagonista(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2Nome = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2Nome = new javax.swing.JTextField();
        jButton1Salvar = new javax.swing.JButton();
        jButton1Apagar = new javax.swing.JButton();
        jButton1Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Jogos");

        jLabel1.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jLabel1.setText("CADASTRAR PERSONAGEM");

        jLabel2Nome.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jLabel2Nome.setText("Nome");

        jTextField1.setText("jTextField1");

        jTextField2Nome.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jTextField2Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2NomeActionPerformed(evt);
            }
        });

        jButton1Salvar.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jButton1Salvar.setText("Salvar");
        jButton1Salvar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton1Salvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SalvarActionPerformed(evt);
            }
        });

        jButton1Apagar.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jButton1Apagar.setText("Apagar");
        jButton1Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ApagarActionPerformed(evt);
            }
        });

        jButton1Cancelar.setFont(new java.awt.Font("Nimbus Roman", 0, 16)); // NOI18N
        jButton1Cancelar.setText("Cancelar");
        jButton1Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2Nome)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 78, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1Salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1Apagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1Cancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Nome)
                    .addComponent(jTextField2Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Salvar)
                    .addComponent(jButton1Apagar)
                    .addComponent(jButton1Cancelar))
                .addGap(35, 35, 35)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CancelarActionPerformed
        this.dispose();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton1CancelarActionPerformed

    private void jButton1SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SalvarActionPerformed
        boolean sucesso;
        
        try{
            ProtagonistaController protagonistaController = new ProtagonistaController();
            sucesso = protagonistaController.cadastrarProtagonista(jTextField2Nome.getText());
            if(sucesso == true){
                JOptionPane.showMessageDialog(null, "Personagem guardado");
            }else {
                JOptionPane.showMessageDialog(null, "Preencha corretamente");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro " + ex);
        }
    }//GEN-LAST:event_jButton1SalvarActionPerformed

    private void jButton1ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ApagarActionPerformed
                jTextField2Nome.setText("");
    }//GEN-LAST:event_jButton1ApagarActionPerformed

    private void jTextField2NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2NomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProtagonista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProtagonista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProtagonista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProtagonista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroProtagonista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Apagar;
    private javax.swing.JButton jButton1Cancelar;
    private javax.swing.JButton jButton1Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2Nome;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2Nome;
    // End of variables declaration//GEN-END:variables

    private void limparTelaCadastroEscritor(ActionEvent evt) {
        
    }
}
